package oracle.jdbc.driver;

import java.sql.ResultSetMetaData;
import java.sql.SQLException;

class OracleReturnResultSet extends ForwardOnlyResultSet {
   private static final String _Copyright_2007_Oracle_All_Rights_Reserved_ = null;
   public static final String BUILD_DATE = "Thu_Apr_04_15:09:24_PDT_2013";
   public static final boolean TRACE = false;

   OracleReturnResultSet(PhysicalConnection var1, OracleStatement var2) throws SQLException {
      super(var1, var2);
   }

   public void close() throws SQLException {
      synchronized(this.statement.connection) {
         super.close();
         this.statement.currentResultSet = null;
         this.statement.returnParamsFetched = false;
         this.statement.rowsDmlReturned = 0;
      }
   }

   public ResultSetMetaData getMetaData() throws SQLException {
      synchronized(this.statement.connection) {
         SQLException var5;
         if (!this.statement.isAutoGeneratedKey) {
            var5 = DatabaseError.createSqlException(this.getConnectionDuringExceptionHandling(), 23);
            var5.fillInStackTrace();
            throw var5;
         } else if (this.closed) {
            var5 = DatabaseError.createSqlException(this.getConnectionDuringExceptionHandling(), 10);
            var5.fillInStackTrace();
            throw var5;
         } else if (this.statement.closed) {
            var5 = DatabaseError.createSqlException(this.getConnectionDuringExceptionHandling(), 9);
            var5.fillInStackTrace();
            throw var5;
         } else {
            AutoKeyInfo var2 = this.statement.autoKeyInfo;
            var2.statement = this.statement;
            var2.connection = this.connection;
            var2.initMetaData(this);
            return var2;
         }
      }
   }
}
